services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/bundles

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=star_burger.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      # - DATABASE_URL = postgres://myuser:938467083we@localhost:5432/mydatabase

    volumes:
      - static_volume:/app/bundles
      - static_volume:/app/staticfiles
      - static_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  static_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/
  db_data:
