services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - bundles_volume:/app/bundles
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=star_burger.settings
    volumes:
      - bundles_volume:/app/bundles
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
  db:
   image: postgres:15
   volumes:
     - db_data:/var/lib/postgresql/data

volumes:
  bundles_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/bundles/
  staticfiles_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/staticfiles/
  media_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/www/media/
  db_data:
    driver_opts:
      o: bind
      type: none
      device: /var/www/db_data