# Generated by Django 3.2.15 on 2024-11-10 16:46

import django.core.validators
from django.db import migrations, models


def fill_price_for_order_product(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    for order_product in OrderProduct.objects.all():
        order_product.price = order_product.product.price
        order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20241109_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(
                null=True,
                blank=True,
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='цена за штуку'
            ),
        ),
        migrations.RunPython(fill_price_for_order_product),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(
                null=False,
                blank=True,
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='цена за штуку'
            ),
        ),
    ]
