# Generated by Django 3.2.15 on 2024-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20241115_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Digital', 'Электронно'), ('Cash', 'Наличностью')], db_index=True, default='Digital', max_length=12, verbose_name='способ оплаты'),
        ),
    ]
