# Generated by Django 3.2.15 on 2024-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Необработан'), ('Cooking', 'Готовится'), ('Delivering', 'Доставляется'), ('Completed', 'Завершён')], db_index=True, default='Unprocessed', max_length=12, verbose_name='статус'),
        ),
    ]
